general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/abyss.toml"
  "~/.config/alacritty/dank-theme.toml"
]


[font]
size = 12.0

[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 5, y = 5 }


[[keyboard.bindings]]
key = "L"
mods = "Control|Shift"
chars = "\u001b[H\u001b[2J\u001b[3J"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
