#!/bin/bash
arg=$1

killall pblur || true
sleep 1
case $arg in
	ne	) ln -sf ~/.config/i3/neutral-config ~/.config/i3/config;;
	bh	) ln -sf ~/.config/i3/black-hole-config ~/.config/i3/config;;
	pr	) ln -sf ~/.config/i3/purple-config ~/.config/i3/config;;
	bl	) ln -sf ~/.config/i3/blue-ghosts-config ~/.config/i3/config;;
	*		) ln -sf ~/.config/i3/neutral-config ~/.config/i3/config
esac

sleep 1
i3-msg restart
sleep 1
