#!/bin/bash
if [[ $(tail -n1 ~/.fehbg | cut -d "'" -f2) = "$CACHEDIR/trans-9" ]]; then
   # Reset wallpaper to original one
    feh --bg-fill ~/backgrounds/purple.png
fi

while true; do
	CURRWORKSPACE=$(wmctrl -d | grep '*' | cut -d ' ' -f1)
	OPENWINDOWS=$(wmctrl -l | cut -d ' ' -f3 | grep $CURRWORKSPACE | wc -l)
	CURRWALLPAPER=$(tail -n1 ~/.fehbg | cut -d "'" -f2)
	if [[ $OPENWINDOWS > 0 ]] || [[ $(pgrep -cl rofi) > 0 ]]  || [[ $(pidof $ADDBLUR) > 0 ]]; then
		if [ $CURRWALLPAPER != "$HOME/backgrounds/purblur.png" ]; then
			feh --bg-fill ~/backgrounds/purblur.png
		fi
	else
		if [ $CURRWALLPAPER != "$HOME/backgrounds/purple.png" ]; then
			feh --bg-fill ~/backgrounds/purple.png
		fi
	fi
	sleep 0.2
done
