#!/bin/bash
MIME=$(echo $1 | cut -d '.' -f2);
BW=$(echo $1 | cut -d '.' -f1);
V="-pblur."
BLURREDWALLPAPER=$BW$V$MIME

if [[ $(pgrep -cl pblur) > 1 ]]; then
	echo 'BLURME: Another instance of blurme me is already running.'
	echo '        Please kill it with fire (pkill blurme) first, then try running me again.'
	exit
fi

if [ $1 =  ""];then
	echo "input image not given"
	exit 0
else
	feh --bg-fill $1
fi

#if [[ $(tail -n1 ~/.fehbg | cut -d "'" -f2) = $BLURREDWALLPAPER ]]; then
#   feh --bg-fill $1
#fi

while true; do
	CURRWORKSPACE=$(wmctrl -d | grep '*' | cut -d ' ' -f1)
	OPENWINDOWS=$(wmctrl -l | cut -d ' ' -f3 | grep $CURRWORKSPACE | wc -l)
	CURRWALLPAPER=$(tail -n1 ~/.fehbg | cut -d "'" -f2)


	if [ -e $BLURREDWALLPAPER ];then
		if [[ $OPENWINDOWS > 0 ]] || [[ $(pgrep -cl rofi) > 0 ]]  || [[ $(pidof $ADDBLUR) > 0 ]]; then
			if [ $CURRWALLPAPER != $BLURREDWALLPAPER ]; then
				feh --bg-fill $BLURREDWALLPAPER
			fi
		else
			if [ $CURRWALLPAPER != $1 ]; then
				feh --bg-fill $1
			fi
		fi
		sleep 0.2
	else 
		A=24
		B=12
		convert $1 -blur $A,$B $BLURREDWALLPAPER
	fi	
done
